apiVersion: v1
kind: Service
metadata:
  name: stream-processing
  namespace: causalops
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: stream-processing
