import numpy as np
import json
import os

val_err_path = r"d:\Projects\CausalOps X\models\anomaly_detection\model1_validation_errors.npy"
out_json = r"d:\Projects\CausalOps X\models\anomaly_detection\model1_threshold.json"

v_err = np.load(val_err_path)
N = len(v_err)

print(f"Validation samples: {N}")
print(f"Validation median: {np.median(v_err):.4f}")
print(f"Validation mean: {np.mean(v_err):.4f}")

# Percentiles
print("\nPERCENTILE THRESHOLDS:")
percentiles = [90, 92, 94, 95, 96, 97, 98, 98.5, 99, 99.5, 99.9]
for p in percentiles:
    t = np.percentile(v_err, p)
    anomalies = np.sum(v_err > t)
    pct = (anomalies / N) * 100
    print(f"P{p:5.1f} | Threshold: {t:7.4f} | Anomalies: {anomalies:4d} | Pct: {pct:5.2f}%")
    
# MAD
print("\nROBUST MAD THRESHOLDS:")
med = np.median(v_err)
mad = np.median(np.abs(v_err - med))
if mad == 0: mad = 1e-6 # prevent div0 just in case
for k in [3, 4, 5, 6, 7]:
    t = med + k * mad
    anomalies = np.sum(v_err > t)
    print(f"k={k} | Threshold: {t:7.4f} | Anomalies: {anomalies:4d} | Pct: {(anomalies/N)*100:5.2f}%")
    
# Select standard 98th percentile for unsupervised LSTM-VAE 
# 98th implies treating top 2% of validation sequence errors as anomalous/novel.
selected_t = np.percentile(v_err, 98)

config = {
    "threshold": float(selected_t),
    "threshold_method": "percentile",
    "percentile": 98,
    "model_checkpoint": "best_vae_model1_20f.pth",
    "input_dim": 20,
    "sequence_length": 20,
    "validation_sample_count": N
}

with open(out_json, "w") as f:
    json.dump(config, f, indent=4)
    
print(f"\nSelected threshold:\n{selected_t:.4f}")
print("Selection method:\n98th Percentile")
print("Reason:\nIn unsupervised anomaly detection without baseline labels, isolating the top 2% (98th percentile) provides a sufficiently robust decision boundary that reliably captures extreme-right distribution tails while aggressively mitigating false-positive operational fatigue generated by bulk validation variances.")
print(f"Threshold saved:\n{out_json.replace(chr(92), '/')}")
